# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import copy_metadata

block_cipher = None

extra_files = copy_metadata('google-api-python-client')

a = Analysis(['db-playmate.py'],
             pathex=['db-playmate', '/Users/lingeman/Library/Caches/pypoetry/virtualenvs/db-playmate-ixWhVYtc-py3.7/lib/python3.7/site-packages', '/Users/lingeman/Dropbox/Workspace/PLAY/db-playmate'],
             binaries=[],
             datas=[['db_playmate/templates','db_playmate/templates'], ['db_playmate/static','db_playmate/static'], ['env','env']] + extra_files,
             hiddenimports=[
            'boxsdk.object.collaboration',
            'boxsdk.object.collaboration_whitelist',
            'boxsdk.object.collaboration_whitelist_entry',
            'boxsdk.object.collaboration_whitelist_exempt_target',
            'boxsdk.object.collection',
            'boxsdk.object.comment',
            'boxsdk.object.device_pinner',
            'boxsdk.object.enterprise',
            'boxsdk.object.events',
            'boxsdk.object.event',
            'boxsdk.object.file',
            'boxsdk.object.file_version',
            'boxsdk.object.file_version_retention',
            'boxsdk.object.folder',
            'boxsdk.object.group',
            'boxsdk.object.group_membership',
            'boxsdk.object.legal_hold',
            'boxsdk.object.legal_hold_policy',
            'boxsdk.object.legal_hold_policy_assignment',
            'boxsdk.object.metadata_cascade_policy',
            'boxsdk.object.metadata_template',
            'boxsdk.object.recent_item',
            'boxsdk.object.retention_policy',
            'boxsdk.object.retention_policy_assignment',
            'boxsdk.object.search',
            'boxsdk.object.storage_policy',
            'boxsdk.object.storage_policy_assignment',
            'boxsdk.object.terms_of_service',
            'boxsdk.object.terms_of_service_user_status',
            'boxsdk.object.trash',
            'boxsdk.object.task',
            'boxsdk.object.task_assignment',
            'boxsdk.object.user',
            'boxsdk.object.upload_session',
            'boxsdk.object.webhook',
            'boxsdk.object.watermark',
            'boxsdk.object.web_link',
            'google-api-python-client',
            'importlib_metadata'],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='db-playmate',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=False )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='db-playmate')

app = BUNDLE(coll,
             name='db-playmate.app',
             icon='icon/PLAY-logo.icns',
             bundle_identifier=None,
             info_plist={
              'CFBundleIdentifier': 'db-playmate',
              'CFBundleName': 'db-playmate',
              'NSPrincipalClass': 'NSApplication',
              'NSAppleScriptEnabled': False,
             },
)
