version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - restore_cache:
        keys:
          - deps-{{ checksum "poetry.lock" }}
      - run:
          name: Install dependencies
          command: |
            poetry install

      - save_cache:
        key: deps-{{ checksum "poetry.lock" }}
        paths:
          - /home/circleci/.cache/pypoetry/virtualenvs

      # black
      - run:
          name: Run Black
          command: |
            poetry run black .
          
      # test
      - name: Test and coverage
      - run:
          command: |
            poetry run pytest --cov=db_playmate tests/
            poetry run coveralls

workflows:
  main:
    jobs:
      - build-and-test
